Models
Mhatw/GetThatJobAPI pull request #11
Opened 2022-07-12 23:09 UTC by frankcdlc

models to:
Types
Requirements
Professional

2022-07-12 23:14 UTC, Mhatw commented on app/models/type.rb
> +        message: "%{value} is not a valid type"}
looks great, can you check typo and add more types like "freelance, remote"

2022-07-13 00:01 UTC, alexisparave94 requested changes
I guess you confuse with column enmail with column name of companies table

2022-07-13 00:19 UTC, frankcdlc commented on app/models/type.rb
> +        message: "%{value} is not a valid type"}
Thanks for the recomendations Mhatw, the changes were made

2022-07-13 00:21 UTC, alexisparave94 commented on db/migrate/20220712220400_add_index_to_company.rb
> +  end
I guess you confuse the name of the column email, it should be name

2022-07-13 00:43 UTC, frankcdlc commented on db/migrate/20220712220400_add_index_to_company.rb
> +  end
You are right, thanks for your corrections

2022-07-13 00:43 UTC, merged